version: "2"
services:
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - '8086:8086'
    # volumes:
    #   - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=cloudflare
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      # - grafana-storage:/var/lib/grafana
      - ../grafana:/etc/grafana/provisioning/
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=${GRAFANA_PLUGINS}
  cloudflare-analytics:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    image: thclpr/cloudflare-analytics-exporter:latest
    volumes:
      - ./config.ini:/app/config.ini:ro
# volumes:
#   influxdb-storage:
#   grafana-storage: